apiVersion: v1
kind: Service
metadata:
  name: test2-kong-svc
  namespace: cutepuppy
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: admin-ssl
      port: 8444
      targetPort: 8444
      protocol: TCP
  selector:
    app: test2-kong
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test2-kong
  namespace: cutepuppy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test2-kong
        app: test2-kong
    spec:
      containers:
        - name: kong
          image: kong:1.0.0_mysql
          env:
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: KONG_DATABASE
              value: mysql
            - name: KONG_MYSQL_USER
              value: kong
            - name: KONG_MYSQL_HOST
              value: test2-mysql.cutepuppy.svc
            - name: KONG_MYSQL_PASSWORD
              value: ${PASSWORD}
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_LOG_LEVEL
              value: debug
            - name: KONG_PLUGINS
              value: "bundled"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: admin
              containerPort: 8001
              protocol: TCP
            - name: proxy
              containerPort: 8000
              protocol: TCP
            - name: proxy-ssl
              containerPort: 8443
              protocol: TCP
            - name: admin-ssl
              containerPort: 8444
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /usr/local/share/lua/5.1/kong
              name: kong-code
      volumes:
        - hostPath:
            path: /etc/localtime
            type: File
          name: localtime
        - hostPath:
            path: /root/kong-1.0.0-mysql-deploy/kong/kong_developed/kong
            type: "DirectoryOrCreate"
          name: kong-code
