apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: web
      nodePort: 8080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
    name: nginx
  name: test-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      name: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      containers:
        - image: nginx:1.15
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              name: admin
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            privileged: true
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /usr/share/nginx/html
              name: html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: html
          hostPath:
            path: /root/nginx/html
