apiVersion: v1
kind: Service
metadata:
  name: postgres-zbb
spec:
  ports:
    - name: psql-port
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-zbb

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-zbb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-zbb
    spec:
      containers:
        - name: postgres-zbb
          image: {{IMAGE_NAME}}
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: pgdata
      volumes:
        - hostPath:
            path: /var/lib/postgresql/data/pgdata
            type: "DirectoryOrCreate"
          name: pgdata
      nodeSelector:
        nodeType: controller
        node: node1
